# git clone https://github.com/alacritty/alacritty-theme.git ./themes
import = [
    "~/AppData/Roaming/alacritty/themes/themes/ubuntu.toml"
]


[window]
padding.x = 5
padding.y = 5

dimensions.columns = 100
dimensions.lines = 25

[font]
size = 12

offset.x = 0  # For letter spacing (default: 0)
offset.y = 1  # For line spacing (default: 0)

normal = {family = "FiraMono Nerd Font", style = "Medium"}


[colors]
# font colour
primary.foreground = "#F5F5DC" # #ecd0a0 #ebdbb2

# makes char behind cursor in normal mode much more visible 
cursor = {text = "#000000", cursor = "#ffffff"}

[cursor]
style.shape = "Beam"
