
# git clone https://github.com/alacritty/alacritty-theme.git ./themes
import = [
    "~/AppData/Roaming/alacritty/themes/themes/ubuntu.toml"
]

[window]
padding.x = 10
padding.y = 10

dimensions.columns = 100
dimensions.lines = 25

[font]
size = 12

offset.x = 0  # For letter spacing (default: 0)
offset.y = 1  # For line spacing (default: 0)

normal.family = "FiraMono Nerd Font" 
